# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zmq_msg.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (
    lambda x: x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='zmq_msg.proto',
    package='ZMQMessage',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\rzmq_msg.proto\x12\nZMQMessage\"\xa0\x02\n\x08ImageMsg\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0bimage_width\x18\x02 \x01(\x05\x12\x14\n\x0cimage_height\x18\x03 \x01(\x05\x12\x17\n\x0fimage_dst_width\x18\x04 \x01(\x05\x12\x18\n\x10image_dst_height\x18\x05 \x01(\x05\x12-\n\x0cimage_format\x18\x06 \x01(\x0e\x32\x17.ZMQMessage.ImageFormat\x12\x30\n\tdata_type\x18\x07 \x01(\x0e\x32\x1d.ZMQMessage.ImageMsg.DataType\x12\x12\n\nimage_name\x18\x08 \x01(\t\"-\n\x08\x44\x61taType\x12\t\n\x05UINT8\x10\x00\x12\t\n\x05INT32\x10\x01\x12\x0b\n\x07\x46LOAT32\x10\x02\"\x87\x01\n\x06ZMQMsg\x12,\n\x08msg_type\x18\x01 \x01(\x0e\x32\x1a.ZMQMessage.ZMQMsg.MsgType\x12%\n\x07img_msg\x18\x02 \x01(\x0b\x32\x14.ZMQMessage.ImageMsg\"(\n\x07MsgType\x12\r\n\tIMAGE_MSG\x10\x00\x12\x0e\n\nFINISH_MSG\x10\x01*\xc3\x01\n\x0bImageFormat\x12\t\n\x05IMG_Y\x10\x00\x12\x0c\n\x08IMG_NV12\x10\x01\x12\x0e\n\nIMG_YUV444\x10\x02\x12\x0b\n\x07IMG_BGR\x10\x03\x12\x0c\n\x08IMG_BGRP\x10\x04\x12\x0b\n\x07IMG_RGB\x10\x05\x12\x0c\n\x08IMG_RGBP\x10\x06\x12\r\n\tTENSOR_U8\x10\x07\x12\r\n\tTENSOR_S8\x10\x08\x12\x0e\n\nTENSOR_F32\x10\t\x12\x0e\n\nTENSOR_S32\x10\n\x12\x0e\n\nTENSOR_U32\x10\x0b\x12\x07\n\x03MAX\x10\x0c\x62\x06proto3'
    ))

_IMAGEFORMAT = _descriptor.EnumDescriptor(
    name='ImageFormat',
    full_name='ZMQMessage.ImageFormat',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='IMG_Y',
            index=0,
            number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_NV12',
            index=1,
            number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_YUV444',
            index=2,
            number=2,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_BGR',
            index=3,
            number=3,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_BGRP',
            index=4,
            number=4,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_RGB',
            index=5,
            number=5,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='IMG_RGBP',
            index=6,
            number=6,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TENSOR_U8',
            index=7,
            number=7,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TENSOR_S8',
            index=8,
            number=8,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TENSOR_F32',
            index=9,
            number=9,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TENSOR_S32',
            index=10,
            number=10,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TENSOR_U32',
            index=11,
            number=11,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='MAX',
            index=12,
            number=12,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=459,
    serialized_end=654,
)
_sym_db.RegisterEnumDescriptor(_IMAGEFORMAT)

ImageFormat = enum_type_wrapper.EnumTypeWrapper(_IMAGEFORMAT)
IMG_Y = 0
IMG_NV12 = 1
IMG_YUV444 = 2
IMG_BGR = 3
IMG_BGRP = 4
IMG_RGB = 5
IMG_RGBP = 6
TENSOR_U8 = 7
TENSOR_S8 = 8
TENSOR_F32 = 9
TENSOR_S32 = 10
TENSOR_U32 = 11
MAX = 12

_IMAGEMSG_DATATYPE = _descriptor.EnumDescriptor(
    name='DataType',
    full_name='ZMQMessage.ImageMsg.DataType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UINT8',
            index=0,
            number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='INT32',
            index=1,
            number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='FLOAT32',
            index=2,
            number=2,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=273,
    serialized_end=318,
)
_sym_db.RegisterEnumDescriptor(_IMAGEMSG_DATATYPE)

_ZMQMSG_MSGTYPE = _descriptor.EnumDescriptor(
    name='MsgType',
    full_name='ZMQMessage.ZMQMsg.MsgType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='IMAGE_MSG',
            index=0,
            number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='FINISH_MSG',
            index=1,
            number=1,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=416,
    serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_ZMQMSG_MSGTYPE)

_IMAGEMSG = _descriptor.Descriptor(
    name='ImageMsg',
    full_name='ZMQMessage.ImageMsg',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='image_data',
            full_name='ZMQMessage.ImageMsg.image_data',
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_width',
            full_name='ZMQMessage.ImageMsg.image_width',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_height',
            full_name='ZMQMessage.ImageMsg.image_height',
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_dst_width',
            full_name='ZMQMessage.ImageMsg.image_dst_width',
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_dst_height',
            full_name='ZMQMessage.ImageMsg.image_dst_height',
            index=4,
            number=5,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_format',
            full_name='ZMQMessage.ImageMsg.image_format',
            index=5,
            number=6,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data_type',
            full_name='ZMQMessage.ImageMsg.data_type',
            index=6,
            number=7,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='image_name',
            full_name='ZMQMessage.ImageMsg.image_name',
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _IMAGEMSG_DATATYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=30,
    serialized_end=318,
)

_ZMQMSG = _descriptor.Descriptor(
    name='ZMQMsg',
    full_name='ZMQMessage.ZMQMsg',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='msg_type',
            full_name='ZMQMessage.ZMQMsg.msg_type',
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='img_msg',
            full_name='ZMQMessage.ZMQMsg.img_msg',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _ZMQMSG_MSGTYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=321,
    serialized_end=456,
)

_IMAGEMSG.fields_by_name['image_format'].enum_type = _IMAGEFORMAT
_IMAGEMSG.fields_by_name['data_type'].enum_type = _IMAGEMSG_DATATYPE
_IMAGEMSG_DATATYPE.containing_type = _IMAGEMSG
_ZMQMSG.fields_by_name['msg_type'].enum_type = _ZMQMSG_MSGTYPE
_ZMQMSG.fields_by_name['img_msg'].message_type = _IMAGEMSG
_ZMQMSG_MSGTYPE.containing_type = _ZMQMSG
DESCRIPTOR.message_types_by_name['ImageMsg'] = _IMAGEMSG
DESCRIPTOR.message_types_by_name['ZMQMsg'] = _ZMQMSG
DESCRIPTOR.enum_types_by_name['ImageFormat'] = _IMAGEFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMsg = _reflection.GeneratedProtocolMessageType(
    'ImageMsg',
    (_message.Message, ),
    {
        'DESCRIPTOR': _IMAGEMSG,
        '__module__': 'zmq_msg_pb2'
        # @@protoc_insertion_point(class_scope:ZMQMessage.ImageMsg)
    })
_sym_db.RegisterMessage(ImageMsg)

ZMQMsg = _reflection.GeneratedProtocolMessageType(
    'ZMQMsg',
    (_message.Message, ),
    {
        'DESCRIPTOR': _ZMQMSG,
        '__module__': 'zmq_msg_pb2'
        # @@protoc_insertion_point(class_scope:ZMQMessage.ZMQMsg)
    })
_sym_db.RegisterMessage(ZMQMsg)

# @@protoc_insertion_point(module_scope)
